# Generated by Django 3.2.13 on 2022-11-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_code', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=50)),
                ('genre_ids', models.JSONField(default={}, null=True)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('backdrop_path', models.TextField()),
            ],
        ),
    ]
