# Generated by Django 3.2.13 on 2022-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_code', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
