# Generated by Django 3.2.13 on 2022-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
