# Generated by Django 3.2.13 on 2022-11-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='mention_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
