# Generated by Django 3.2.13 on 2022-11-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomment_mention_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', to='articles.articlecomment'),
        ),
    ]
