# Generated by Django 3.2.13 on 2022-11-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0003_alter_user_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
