# Generated by Django 3.2.13 on 2022-11-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_search_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='search_history',
        ),
    ]
